name: Build README
on:
  push:
    branches:
    - master
    paths-ignore:
    - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name:
      uses: cflynn07/github-action-til-autoformat-readme@1.1.0
      with:
        list_most_recent: 5